language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get install python-pygame
  - sudo apt-get install python-scipy
  - sudo apt-get install python-numpy 
  - sudo apt-get install python-matplotlib
install: "pip install -r requirements.txt"
before_script:
  - git clone git://github.com/pybrain/pybrain.git pybrain
  - cd pybrain
  - python setup.py install
  - cd ..
# command to run tests
script: python pygame_main.py no